name: 
channels:
  - conda-forge
dependencies:
  - datasets
  - matplotlib
  - numpy
  - opencv
  - pandas
  - python=3.12
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - timm
  - torchvision
  - tqdm
  - transformers
